---
title: A night in Japan
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
email: post@espenpedersen.net
description: A blog about japan
baseurl: ''
url: ''
twitter_username: 
github_username: epedersen
theme: minima
plugins:
- jekyll-feed
